### ISSUE TITLE
Setting Units in Device Config is not Working

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#564] opened 2020-03-02 17:37 UTC
### Deliverables
- [ ] Identify bug
- [ ] Fix bug
- [ ] Find out what went wrong, as this was working before and now it is not. Ask colleagues, use git history, etc. and determine way we can improve our process to avoid issues like this in the future (e.g., broader test coverage, more standardized QA, whatever you think is best given however it occurred, etc.)

### To Recreate
On the Stem Cell Reactor
[In the device settings page](https://dev.ospin-app.com/device/131c3c27-bdf3-4a45-93d4-449b4578b3ee/setup)
Attempt to set default units by either mode
See failure:

![image](https://user-images.githubusercontent.com/17087405/75701688-7b41cd00-5cb4-11ea-9344-1710db186e08.png)

**Comment by vdiezel** [comment] 2020-03-03 10:43
issue was caused by a persisted `eventTriggers` key on a stream configuration of the device config. It got there when I was testing eventTriggers being set as device default. The change just wasn't deployed yet - this will be fixed once we have CD for hambda.

**Closed by vdiezel** 2020-03-03 10:43 UTC
Labels: bug, urgent
