### ISSUE TITLE
Change name of the reactor

### ISSUE THREAD

**Issue by jmoralesdalmau** [ospin-web-dev/REACTor#418] opened 2019-12-17 11:15 UTC
I tried to change the name of the OD-001 Athen reactor as "Stem Cell Generator" and I could not.

I clicked in the icon, introduced a named and intro, but did not work. 
Actually, user cannot double click to change the name because goes directly to the processes page. It not very user friendly to change the name it that sense. 
I hope it is useful. 
Thanks

**Describe the bug**

**To Reproduce**
_(providing device and process IDs is very helpful when applicable! You can find them in the url)_

**Expected behavior**

**Screenshots**
(an easy way to do this is to make sure an image is copied to clipboard, then you can just `ctrl + v` right in line here and GitHub will do the rest!)

**Environment**
 - [ ] Development (https://dev.ospin-app.com)
 - [ ] Production (https://ospin-app.com)

**DeviceID / ProcessID (if applies)**
The IDs can be found in the browser in the url: `ospin-app.com/device/{deviceId}/procecss/{processID}`

**Additional context**

**Comment by DanielSeehausen** [comment] 2020-01-06 12:03
could not reproduce - closing for now. 
Best guess is that user was not connected to internet. Feature to display the global 'Offline' banner should clear up this confusion and bad user experience.

**Closed by DanielSeehausen** 2020-01-06 12:03 UTC
Labels: bug, triage required
