### ISSUE TITLE
Reactor#162 deploy environment spike and webdev proposal

### ISSUE THREAD

**Issue by petros751** [ospin-web-dev/REACTor#176] opened 2019-09-13 12:52 UTC
#162  I set up the github REACTor repository into netlify platform.

**Comment by petros751** [comment] 2019-09-13 12:55
I have to found out how can we change the url subdomain from netlify and add the name of the branch as a netlify subdomain.

**Comment by petros751** [comment] 2019-09-13 13:37
https://www.netlify.com/docs/custom-domains/ if you scroll down in this page you will see the **Branch Subdomain** topic @vdiezel

**Comment by DanielSeehausen** [comment] 2019-09-16 16:18
I am going to close this as a duplicate of #162 !
Unless I am mistaken @petros751 , this seems to be all present in the other issue. 
Re-open and let me know if I have made a mistake please!

**Closed by DanielSeehausen** 2019-09-16 16:18 UTC
