### ISSUE TITLE
SPIKE: the shown time of the hole process start from Zero

### ISSUE THREAD

**Issue by aahmed2021** [ospin-web-dev/REACTor#395] opened 2019-12-11 11:17 UTC
All information you provide is _extremely_ helpful to us! Thank you for taking the time.

**Describe the bug**
i have a running process with different phases. if I change a parameter in the phase or great  a new phase and click the button “go to the next Phase”, the shown time of the hole process start from Zero. 

**To Reproduce**
1. go to the device and great a new process with many phases
2. start the process wait a minute and go to the next Phase, 
3. go back to my processes and it should Nothing changed, the time still correctly
3. if you change something in one phase (like the Speed of th pump) or if you great a new phase during a running process and click the go to the next phase
5. go back to my processes, you should see now the time is: 0h00m, that stays until you refresh the website 
6. if you go back to my devices and open the process again the shown time is still from the last phase, not the hole process. that stays until you refresh the website 

**Expected behavior**

**Screenshots**
as you see in this Pictures 
![image](https://user-images.githubusercontent.com/56728314/70615584-f68f6780-1c0c-11ea-85d7-14c93010bd10.png)
![image](https://user-images.githubusercontent.com/56728314/70615971-b67cb480-1c0d-11ea-959d-73b60c388b1b.png)

**Environment**
 - [ ] Development (https://dev.ospin-app.com)
 - [ x ] Production (https://ospin-app.com)

**Comment by vdiezel** [comment] 2020-01-11 10:46
couldn't reproduce this issue. I'll close it and we see if this friend shows up again!

**Closed by vdiezel** 2020-01-11 10:46 UTC
Labels: 3, UI, bug, urgent
