### ISSUE TITLE
Shared process needs log out to be seen

### ISSUE THREAD

**Issue by ninabuffi** [ospin-web-dev/REACTor#383] opened 2019-12-09 13:01 UTC
All information you provide is _extremely_ helpful to us! Thank you for taking the time.

**Describe the bug**
When user1 shares process with user2, use 2 needs to log out and log in again to see that process.

**To Reproduce**
1. User1 shares process with user2 (user2 has access to the corresponding machine).
2. User2 can not see the process in the process view.
3. User2 logs out and logs in again: the process appears in the process view. 

**Expected behavior**
No log out and log in needed.

**Screenshots**
No screenshots.

**Environment**
Production (https://ospin-app.com)

**DeviceID / ProcessID (if applies)**
DeviceID: 5602794b-6eeb-449b-9f6e-868a66fd1547
ProcessID: 360acc26-d983-4e49-9149-b81afbf329e7

**Additional context**

**Comment by vdiezel** [comment] 2019-12-18 12:13
Following the described steps I was not able to reproduce the issue. I'll close this issue and we will reopen it if the error happens again. I can image it can take some time until data is propagated between MongoDB shards? While user 1 did the request to shard 1 and updated the user there, user 2 was talking to shard 2 which didn't have the changes yet. In this case, logging in and out didn't fix the issue, it was just coincidence. 

We need more context to figure out what is going on.

**Closed by vdiezel** 2019-12-18 12:13 UTC
Labels: 3, bug
