### ISSUE TITLE
phase modification modal display ui off

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#311] opened 2019-11-21 14:23 UTC
this is how it looks now

![image](https://user-images.githubusercontent.com/17087405/69346337-e66e1300-0c72-11ea-9eb6-a4a270cdb853.png)

**Comment by vdiezel** [comment] 2019-11-21 14:45
duplicate of #307 !

**Closed by vdiezel** 2019-11-21 14:45 UTC
Labels: UI, bug, urgent
