### ISSUE TITLE
Provide feedback on process start

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#752] opened 2020-05-12 13:40 UTC
### Feature Description / Problem Solved by Feature
As a user on the processes page with an executable process in view,
when I hit the start process button,
i receive some visual feedback that it is loading/my command is being processed

also, when I it the end/pause/change phase button, I receive similar feedback that my process is underway
I receive

(currently, it doesn't change display until the device successfully emits that it is changing state)

---

### Screenshots/Images/Links

![image](https://user-images.githubusercontent.com/17087405/81698875-e3582080-9466-11ea-9744-703a6ccf163f.png)

**Comment by vdiezel** [comment] 2020-05-12 14:07
duplicate of #658 :)

**Closed by vdiezel** 2020-05-12 14:07 UTC
Labels: UI
